# Generated by Django 4.1.2 on 2024-07-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RayoMaqueen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
